<script lang="ts">
	import Vue from './badges/Vue.svelte';
	import DevReleaseCard from './DevReleaseCard.svelte';
</script>

<DevReleaseCard title="MoodleREST">
	An unofficial API reference for <a href="https://moodle.org/">Moodle</a>
	web services, generated by regex matching their source code.

	{#snippet action()}
		<a href="https://doodlezucc.github.io/MoodleREST/" class="button">
			API Reference <i class="fas fa-arrow-up-right-from-square"></i>
		</a>
		<a href="https://github.com/doodlezucc/MoodleREST" class="button">
			Repository <i class="fab fa-github"></i>
		</a>
	{/snippet}

	{#snippet badges()}
		<Vue />
	{/snippet}
</DevReleaseCard>
